name: Test Dockerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged # Optional: grants privileges to Docker
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          source ~/.profile

      # Build the Docker containers
      - name: Build Docker images
        run: docker-compose build

      # Run the tests inside Docker container (equivalent to your test-local.sh)
      - name: Run tests
        run: |
          docker compose up -d
          docker compose exec backend sh -c '/app/tests-start.sh -x'
